# Generated by Django 4.0.4 on 2022-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fabriquant', models.CharField(max_length=100)),
                ('date_production', models.DateField(blank=True, null=True)),
                ('nombre_avion', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
